#!/bin/bash
  curl -sL nxtrace.org/nt | bash
  function BenchExec_Traceroute_Core() {
    /usr/local/bin/nexttrace -j -q 1 -m "$3" -n -g en -c -M "$1"| sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g"|grep -v -e 'NextTrace v' -e 'NextTrace API' -e 'IP Geo Data'|tee -a /tmp/trace/"${4}.json"
}

function BenchAPI_Traceroute_Pretty() {
BenchExec_Traceroute_Core "$1" "icmp" "$3" "$4"
}

GlobalVar_TracerouteMode='icmp'
GlobalVar_TracerouteMaxHop=30
        BenchAPI_Traceroute_Pretty "113.209.132.146" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Unicom (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "45.126.112.33" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Telecom (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "183.242.65.12" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Mobile (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "103.116.79.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Unicom (Shanghai, IPv4)"
        BenchAPI_Traceroute_Pretty "210.5.157.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Telecom (Shanghai, IPv4)"
        BenchAPI_Traceroute_Pretty "117.144.213.77" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Mobile (Shanghai, IPv4)"
        BenchAPI_Traceroute_Pretty "210.21.4.130" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Unicom (Guangzhou, IPv4)"
        BenchAPI_Traceroute_Pretty "113.108.209.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Telecom (Guangzhou, IPv4)"
        BenchAPI_Traceroute_Pretty "183.232.48.167" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Mobile (Guangzhou, IPv4)"
        BenchAPI_Traceroute_Pretty "210.13.66.238" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Unicom CUII/AS9929 (Shanghai, IPv4)"
        BenchAPI_Traceroute_Pretty "58.32.0.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Telecom CN2/AS4812 (Shanghai, IPv4)"
        BenchAPI_Traceroute_Pretty "14.131.128.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Dr.Peng HomeNetwork (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "211.167.230.100" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China Dr.Peng BizNetwork (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "101.6.6.6" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China CERNET (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "159.226.254.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China CSTNET (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "211.156.140.17" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "China RTVB (Beijing, IPv4)"
        BenchAPI_Traceroute_Pretty "203.160.95.218" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港联通"
        BenchAPI_Traceroute_Pretty "203.215.232.173" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港电信"
        BenchAPI_Traceroute_Pretty "203.8.25.187" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港电信CN2"
        BenchAPI_Traceroute_Pretty "203.142.105.9" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港移动"
        BenchAPI_Traceroute_Pretty "218.188.104.30" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港HGC"
        BenchAPI_Traceroute_Pretty "210.6.23.239" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港HKBN"
        BenchAPI_Traceroute_Pretty "202.85.125.60" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港PCCW"
        BenchAPI_Traceroute_Pretty "202.123.76.239" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港TGT"
        BenchAPI_Traceroute_Pretty "59.152.252.242" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-香港WTT"
        BenchAPI_Traceroute_Pretty "203.215.233.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-中国电信"
        BenchAPI_Traceroute_Pretty "183.91.61.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-中国电信CN2"
        BenchAPI_Traceroute_Pretty "118.201.1.11" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-Singtel"
        BenchAPI_Traceroute_Pretty "203.116.46.33" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-StarHub"
        BenchAPI_Traceroute_Pretty "118.189.184.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-M1"
        BenchAPI_Traceroute_Pretty "118.189.38.17" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-M1 GamePro"
        BenchAPI_Traceroute_Pretty "13.228.0.251" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "新加坡-AWS"
        BenchAPI_Traceroute_Pretty "61.213.155.84" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-NTT"
        BenchAPI_Traceroute_Pretty "202.232.15.70" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-IIJ"
        BenchAPI_Traceroute_Pretty "210.175.32.26" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-SoftBank"
        BenchAPI_Traceroute_Pretty "106.162.242.108" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-KDDI"
        BenchAPI_Traceroute_Pretty "203.215.236.3" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-中国电信"
        BenchAPI_Traceroute_Pretty "202.55.27.4" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-中国电信CN2"
        BenchAPI_Traceroute_Pretty "13.112.63.251" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "日本-AWS"
        BenchAPI_Traceroute_Pretty "210.114.41.101" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "韩国-KT"
        BenchAPI_Traceroute_Pretty "175.122.253.62 " "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "韩国-SK"
        BenchAPI_Traceroute_Pretty "211.174.62.44" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "韩国-LG"
        BenchAPI_Traceroute_Pretty "218.185.246.3" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "韩国-中国电信CN2"
        BenchAPI_Traceroute_Pretty "13.124.63.251" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "韩国-AWS"
        BenchAPI_Traceroute_Pretty "202.133.242.116" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾Chief"
        BenchAPI_Traceroute_Pretty "210.200.69.90" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾APTG"
        BenchAPI_Traceroute_Pretty "203.75.129.162" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾CHT"
        BenchAPI_Traceroute_Pretty "219.87.66.3" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾TFN"
        BenchAPI_Traceroute_Pretty "211.73.144.38" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾FET"
        BenchAPI_Traceroute_Pretty "61.63.0.102" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾KBT"
        BenchAPI_Traceroute_Pretty "103.31.196.203" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "中国-台湾TAIFO"
        BenchAPI_Traceroute_Pretty "218.30.33.17" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-洛杉矶-中国电信"
        BenchAPI_Traceroute_Pretty "66.102.252.100" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-洛杉矶-中国电信CN2"
        BenchAPI_Traceroute_Pretty "63.218.42.81" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-洛杉矶-PCCW"
        BenchAPI_Traceroute_Pretty "66.220.18.42" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-洛杉矶-HE"
        BenchAPI_Traceroute_Pretty "173.205.77.98" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-洛杉矶-GTT"
        BenchAPI_Traceroute_Pretty "12.169.215.33" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-旧金山-ATT"
        BenchAPI_Traceroute_Pretty "66.198.181.100" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-纽约州-TATA"
        BenchAPI_Traceroute_Pretty "218.30.33.17" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-圣何塞-中国电信"
        BenchAPI_Traceroute_Pretty "23.11.26.62" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-圣何塞-NTT"
        BenchAPI_Traceroute_Pretty "72.52.104.74" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-费利蒙-HE"
        BenchAPI_Traceroute_Pretty "205.216.62.38" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-拉斯维加斯-Level3"
        BenchAPI_Traceroute_Pretty "64.125.191.31" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-圣何塞-ZAYO"
        BenchAPI_Traceroute_Pretty "149.127.109.166" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "美国-阿什本-Cogentco"
        BenchAPI_Traceroute_Pretty "80.146.191.1" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-Telekom"
        BenchAPI_Traceroute_Pretty "82.113.108.25" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-O2"
        BenchAPI_Traceroute_Pretty "139.7.146.11" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-Vodafone"
        BenchAPI_Traceroute_Pretty "118.85.205.101" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-中国电信"
        BenchAPI_Traceroute_Pretty "5.10.138.33" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-中国电信CN2"
        BenchAPI_Traceroute_Pretty "213.200.65.70" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-GTT"
        BenchAPI_Traceroute_Pretty "212.20.150.5" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "德国-法兰克福-Cogentco"
        BenchAPI_Traceroute_Pretty "194.62.232.211" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "英国-Vodafone"
        BenchAPI_Traceroute_Pretty "213.121.43.24" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "英国-BT"
        BenchAPI_Traceroute_Pretty "80.231.131.34" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "英国-伦敦-TATA"
        BenchAPI_Traceroute_Pretty "118.85.205.181" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "俄罗斯-中国电信"
        BenchAPI_Traceroute_Pretty "185.75.173.17" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "俄罗斯-中国电信CN2"
        BenchAPI_Traceroute_Pretty "87.226.162.77" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "俄罗斯-莫斯科RT"
        BenchAPI_Traceroute_Pretty "217.150.32.2" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "俄罗斯-莫斯科TTK"
        BenchAPI_Traceroute_Pretty "195.34.32.71" "${GlobalVar_TracerouteMode}" "${GlobalVar_TracerouteMaxHop}" "俄罗斯-莫斯科MTS"
